# Generated by Django 4.2.2 on 2023-06-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amphitheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('eventType', models.CharField(max_length=50)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('eventType', models.CharField(max_length=50)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SeminarHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('eventType', models.CharField(max_length=50)),
                ('describe', models.TextField()),
            ],
        ),
    ]
