# Generated by Django 4.2.2 on 2023-06-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatapp', '0002_amphitheatre_ground_seminarhall'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ground',
            new_name='SportsGround',
        ),
    ]
