# Generated by Django 4.2.2 on 2023-06-20 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formatapp', '0004_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Your_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('amphitheatre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formatapp.amphitheatre')),
                ('auditorium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formatapp.auditorium')),
                ('seminar_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formatapp.seminarhall')),
                ('sports_ground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formatapp.sportsground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
