# Generated by Django 4.2.2 on 2023-06-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatapp', '0005_your_activity_delete_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='your_activity',
            name='booking_date',
        ),
    ]
