# Generated by Django 4.2.2 on 2023-07-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatapp', '0009_alter_auditorium_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditorium',
            old_name='describe',
            new_name='eventDes',
        ),
    ]
