# Generated by Django 4.2.2 on 2023-07-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatapp', '0010_rename_describe_auditorium_eventdes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditorium',
            old_name='eventDes',
            new_name='describe',
        ),
    ]
